### ISSUE TITLE
Is this project finished? I can't reproduce it

### ISSUE THREAD

**Issue by mu001999** [ldm0/cargo-bug-repo#1]

**Comment by ldm0** [comment]
Yeah, this project was finished.
I've added a test here[9d9ca5249d1e120c9460f16cfcdb2081a6eba4a6](https://github.com/rust-lang/cargo/pull/13863/files#diff-0ae66944868ae7d368f205f44cda3aae008c95863884e510f47adda728dfac6bR2918), which will fail without fixing.

**Comment by mu001999** [comment]
I couldn't reproduce it on my machine, Linux, Mac and WSL.
```
~/r/cargo-bug-repo @ master » cargo check
    Updating `tuna` index
   Compiling serde v1.0.194
    Checking once_cell v1.19.0 (/home/mu001999/repos/cargo-bug-repo/vendor/once_cell_1_19)
    Checking once_cell v0.1.0 (/home/mu001999/repos/cargo-bug-repo/vendor/once_cell_0_1)
    Checking bar v0.1.0 (/home/mu001999/repos/cargo-bug-repo/vendor/bar)
    Checking foo v0.1.0 (/home/mu001999/repos/cargo-bug-repo/vendor/foo)
    Checking cargo-bug-repo v0.1.0 (/home/mu001999/repos/cargo-bug-repo)
    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
```

**Comment by ldm0** [comment]
Well, the `Updating tuna index` is exactly what I would expect. This is a minimal reproduction crate for redundant index fetching. You will see index updating every time you compile this crate, which wouldn't occur to a normal crate.

**Comment by ldm0** [comment]
This is the bug behaviour, index is always updated:
![image](https://github.com/ldm0/cargo-bug-repo/assets/31354274/6f66f010-5e6f-494e-95ef-1f0087991273)

This is the expected behaviour:
![image](https://github.com/ldm0/cargo-bug-repo/assets/31354274/424c41e0-78c9-4f07-bf06-bc86a4c467fa)

This is quite subtle, you may not even notice it if your internet is fast enough. :-P

**Comment by mu001999** [comment]
I misunderstood. I thought it would get stuck in index fetching every time, lol.
